### PR TITLE
added basic support for nvme devices

### PR DESCRIPTION
**Pull request by tavisma**

### CODE REVIEW

**Comment by markstos** [comment]
The patch also needs:

 * Making sure `nvme` is installed as a package dependency
 * Failing gracefully if `nvme` is missing
 * Documenting NVME support.

**Comment by tavisma** [comment]
Found a few other bugs as well, will have a look

**Comment by tavisma** [comment]
Looks like nvme-cli is only available starting from Ubuntu Xenial (16.04) and associated Debian release but this package supports systems back to ubuntu 8.04

The NVME detection logic only triggers when it finds an nvme device name in the list, which isn't possible for older systems (which lack NVME support) so i'm not sure how you guys want to handle this

**Comment by markstos** [comment]
We only need to support active Ubuntu LTS releases, which is currently 16.04 and 18.04. Support for older releases can be dropped. So the nvme-cli dependency is easy if it's in the base system. Some people will try to run this on unsupported systems anyway, so it's still helpful to check if the binary is present.

**Comment by tavisma** [comment]
i've added the nvme-cli package (available from ubuntu 16.04 onward) as a dependency and added some additional checking around the execution of the nvme binary

**Comment by markstos** [comment]
@tavisma  Please test this snap release. It is the path forward for getting a release out that works on 16.04 and 18.04. (It doesn't include the NVME patches yet). 

     snap install ec2-consistent-snapshot --channel=edge --devmode

I built it on Bionic. It's my first Snap package. It would be nice to improve the "confinement" setting so we don't have to publish it in "devmode". You are welcome to work on that.  However, the permissions it has in devmode are the same as it has in the `.deb` file.

So, it's no less secure, it's just that Snaps enable the possibility of being *more* secure by further limiting the filesystem access of your packages.

**Comment by ablundgren** [comment]
I've tested this fix on amazon linux1 and can confirm that it works there on r5.xlarge machines.

**Comment by markstos** [comment]
@ablundgren Did you test the fix via snap or some other method? I didn't realize Snaps were support on AWS Linux 1.

**Comment by ablundgren** [comment]
For ec2-consistent snapshot, we build it ourselves since there is no rpm.

**Comment by markstos** [comment]
I no longer intend to help maintain this package after running into problems with the Perl stack myself like #76. No Perl SDK is supported by AWS, complicating debugging. 

I wrote a similar tool in Bash that uses the officially supported `aws` CLI tool.  https://github.com/RideAmigosCorp/ec2-consistent-snapshot.sh

If you want to see about becoming a maintainer of this project you can ask @ehammond.

**Comment by mpdude** [comment]
I have a slight modification of this over at #109, and also a corresponding `.deb` package as `ec2-consistent-snapshot-0.71-webfactory2` at https://launchpad.net/~webfactory/+archive/ubuntu/ppa/+packages

**Comment by ehammond** [comment]
Thanks for submitting this. Unfortunately, this project is no longer under development in this repo. Anybody is welcome to fork the project and continue development if there is interest.

**Pull request closed without merging**
